name = "HmtArchive"
uuid = "1e7b0059-6550-4515-8382-5d3f2046a0a7"
authors = ["nsmith "]
version = "0.1.0"

[deps]
CitableObject = "e2b2f5ea-1cd8-4ce8-9b2b-05dad64c2a57"
CitableTeiReaders = "b4325aa9-906c-402e-9c3f-19ab8a88308e"
CitableText = "41e66566-473b-49d4-85b7-da83b66615d8"
EditionBuilders = "2fb66cca-c1f8-4a32-85dd-1a01a9e8cd8f"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"

[compat]
EditionBuilders = "0.2.5"
